# Lighthouse-Badger | GitHub Action Workflow
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to a selected target repository
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflow
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger'

########################################################################
# DEFINE YOUR TOKEN, INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# TOKEN and INPUTS as environmental variables
env:
  # Token for all triggers (INSERT ONLY THE NAME NEVER THE REAL VALUE)
  TOKEN: ${{ secrets.SITDISCH_REPO_TOKEN }} # insert ${{ secrets.<TOKEN_NAME> }} and replace <TOKEN_NAME>
  # 
  # Inputs for not manually triggered workflows (if empty, defaults are used)
  URLS: 'https://mythemeway.github.io/Light-Particle/ https://mythemeway.github.io/Light-Particle/projects/2020/10/31/project-1.html' # URL(s) to be checked e.g. 'https://github.com/sitdisch https://github.com/mythemeway'
  REPOSITORY: # target repository e.g. 'dummy/mytargetrepo'
  BRANCH: # target branch e.g. 'master'
  BADGES-ARGS: # badge-style '-b {flat,...}', preceding-label '-l "Lighthouse "', output-path '-o lighthouse_results/dummy', save-report '-r', single-badge '-s'
  RESULTS-TYPE: # 'mobile', 'desktop' or 'both'
  MOBILE-LIGHTHOUSE-PARAMS: # Lighthouse parameters mobile audit
  DESKTOP-LIGHTHOUSE-PARAMS: # Lighthouse parameters desktop audit
  USER-NAME: # user who should commit e.g. 'dummy'
  USER-EMAIL: # e.g. 'dummy@gmail.com'
  COMMIT-MESSAGE: # e.g. 'Lighthouse results added'
  # 
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE DEFAULT VALUES
  DEFAULT-REPOSITORY: 'sitdisch/cloud' # repo with this file
  DEFAULT-BRANCH: 'master'
  DEFAULT-BADGES-ARGS: '-b pagespeed -o lighthouse_results/light_particle -r'
  DEFAULT-RESULTS-TYPE: 'both'
  DEFAULT-MOBILE-LIGHTHOUSE-PARAMS: '--throttling.cpuSlowdownMultiplier=2'
  DEFAULT-DESKTOP-LIGHTHOUSE-PARAMS: '--preset=desktop --throttling.cpuSlowdownMultiplier=1'
  DEFAULT-USER-NAME: 'github-actions[bot]'
  DEFAULT-USER-EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  DEFAULT-COMMIT-MESSAGE: 'Lighthouse Results Refreshed | Light-Particle'

# TRIGGERS
on:
  page_build:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  # 
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE WORKFLOW_DISPATCH HERE
  workflow_dispatch:
    inputs:
      urls:
        description: 'URL(s) to be checked'
        required: true
        default: 'https://mythemeway.github.io/Light-Particle/ https://mythemeway.github.io/Light-Particle/projects/2020/10/31/project-1.html'
      repository:
        description: 'Target repository'
        required: true
        default: 'sitdisch/cloud'
      branch:
        description: 'Target branch'
        required: true
        default: 'master'
      badges-args:
        description: 'Badges arguments: -b, -l, -o, -r, -s'
        required: true
        default: '-b pagespeed -o lighthouse_results/light_particle -r'
      results-type:
        description: 'Results type: mobile, desktop or both'
        required: true
        default: 'both'
      mobile-lighthouse-params:
        description: 'Lighthouse parameters mobile audit'
        required: true
        default: '--throttling.cpuSlowdownMultiplier=2'
      desktop-lighthouse-params:
        description: 'Lighthouse parameters desktop audit'
        required: true
        default: '--preset=desktop --throttling.cpuSlowdownMultiplier=1'
      user-name:
        description: 'User who should commit'
        required: true
        default: 'github-actions[bot]'
      user-email:
        description: 'User e-mail address'
        required: true
        default: '41898282+github-actions[bot]@users.noreply.github.com'
      commit-message:
        description: 'Commit message'
        required: true
        default: 'Lighthouse Results Refreshed | Light-Particle'

########################################################################
# YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

# Jobs
jobs:
  lighthouse-badger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.event.inputs.repository || env.REPOSITORY || env.DEFAULT-REPOSITORY }}
          token: ${{ env.TOKEN }}
          ref: ${{ github.event.inputs.branch || env.BRANCH || env.DEFAULT-BRANCH }}
      - uses: actions/checkout@v2.3.4
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested
      - uses: myactionway/lighthouse-badger-action@v1.0
        with:
          urls: ${{ github.event.inputs.urls || env.URLS }}
          badges-args: ${{ github.event.inputs.badges-args || env.BADGES-ARGS || env.DEFAULT-BADGES-ARGS }}
          results-type: ${{ github.event.inputs.results-type || env.RESULTS-TYPE || env.DEFAULT-RESULTS-TYPE }}
          mobile-lighthouse-params: ${{ github.event.inputs.mobile-lighthouse-params || env.MOBILE-LIGHTHOUSE-PARAMS || env.DEFAULT-MOBILE-LIGHTHOUSE-PARAMS }}
          desktop-lighthouse-params: ${{ github.event.inputs.desktop-lighthouse-params || env.DESKTOP-LIGHTHOUSE-PARAMS || env.DEFAULT-DESKTOP-LIGHTHOUSE-PARAMS }}
          user-name: ${{ github.event.inputs.user-name || env.USER-NAME || env.DEFAULT-USER-NAME }}
          user-email: ${{ github.event.inputs.user-email || env.USER-EMAIL || env.DEFAULT-USER-EMAIL }}
          commit-message: ${{ github.event.inputs.commit-message || env.COMMIT-MESSAGE || env.DEFAULT-COMMIT-MESSAGE }}
